### ISSUE TITLE
Some shows fail to load due to empty verticalPhotos list

### ISSUE THREAD

**Issue by pr11t** [yllar/plugin.video.jupiter.err.ee#3]
Playing some shows fails with the following error:
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <type 'exceptions.IndexError'>
Error Contents: list index out of range
Traceback (most recent call last):
    File "/home/priit/.kodi/addons/plugin.video.jupiter.err.ee/addon.py", line 388, in <module>
    router(sys.argv[2][1:])
    File "/home/priit/.kodi/addons/plugin.video.jupiter.err.ee/addon.py", line 376, in router
    get_section(params['section'], params['sub'])
    File "/home/priit/.kodi/addons/plugin.video.jupiter.err.ee/addon.py", line 205, in get_section
    if 'photoUrlOriginal' in day['verticalPhotos'][0]:
IndexError: list index out of range
-->End of Python script error report<--
```
To reproduce, try opening "#Melomaania" from Saated A-Ü.

Jupiter API returns an empty verticalPhotos list in some cases, but this is not handled.
https://github.com/yllar/plugin.video.jupiter.err.ee/blob/9d155d3aa328c4d3a2f84eabf56e42345548eff6/addon.py#L181-L182

And thank you for all the good work on the Kodi plugins :)

**Comment by yllar** [comment]
should be fixed in v0.0.7

**Comment by janwil123** [comment]
I am still getting a similar error in version 0.0.7 when trying to load 'Filmid' menu item for example. 

2021-08-30 20:24:57.022 T:20306   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/home/janwil/.kodi/addons/plugin.video.jupiter.err.ee/addon.py", line 347, in <module>
                                                       router(sys.argv[2][1:])
                                                     File "/home/janwil/.kodi/addons/plugin.video.jupiter.err.ee/addon.py", line 333, in router
                                                       get_category(params['category'])
                                                     File "/home/janwil/.kodi/addons/plugin.video.jupiter.err.ee/addon.py", line 128, in get_category
                                                       if 'photoUrlOriginal' in content['verticalPhotos'][0]:
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--

**Comment by yllar** [comment]
Please try 0.0.8, this error should be fixed.

**Comment by janwil123** [comment]
Indeed, "Filmid" menu item now works as well. 

Thanks a lot and keep up the good work!
Jan
